export { default as RootTemplate } from './RootTemplate/RootTemplate';
export { default as QuizRegister } from './QuizRegister/QuizRegister';
export { default as Category } from './Category/Category';
export { default as CategoryDetail } from './CategoryDetail/CategoryDetail';
export { default as Quiz } from './Quiz/Quiz';
export { default as QuizEdit } from './QuizEdit/QuizEdit';
export { default as QuizFilter } from './QuizFilter/QuizFilter';
export { default as FilterParse } from './QuizFilter/FilterParse';
export { default as Auth } from './Auth/Auth';
